#import <Foundation/Foundation.h>

#define MY_OFFICE @"Офисы"
#define MY_TARIF @"Тарифы"
#define MY_SERVICE @"Услуги"
#define MY_WORKER @"Сотрудники"
#define MY_ROUTER @"Оборудование"
#define MY_APPLICATION @"Заявки"
#define MY_CONTRACT @"Договоры"
#define MY_DOLZ @"Должности"
#define MY_MODEL @"Прайс лист"
#define MY_GRAPH @"Графики работы"
#define MY_SEO @"Доходы компании"

#define CONTROLLER_OFFICE @"newOffice"
#define CONTROLLER_TARIF @"newTarif"
#define CONTROLLER_SERVICE @"newService"
#define CONTROLLER_WORKER @"newWorker"
#define CONTROLLER_ROUTER @"newRouter"
#define CONTROLLER_APPLICATION @"newApplication"
#define CONTROLLER_CONTRACT @"newContract"
#define CONTROLLER_DOLZ @"newDolz"
#define CONTROLLER_MODEL @"newModel"
#define CONTROLLER_GRAPH @"newGraph"

#define TABLE_MODEL @"Model"
#define TABLE_OFFICE @"Office"
#define TABLE_TARIF @"Tarif"
#define TABLE_SERVICE @"Service"
#define TABLE_WORKER @"Worker"
#define TABLE_ROUTER @"Router"
#define TABLE_APPLICATION @"Application"
#define TABLE_CONTRACT @"Contract"
#define TABLE_DOLZ @"Dolz"
#define TABLE_CONTRACT_SERVICE @"CortractService"
#define TABLE_GRAPH @"Graph"